<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Document</title>
    </head>
    <body>
        <script>

        const pro1=new Promise((resolve,reject)=>{
            throw 1;
        })
        const pro2=pro1.then(result=>{
            return result*2;
        },err=>{
            err*3;
        })
        console.log(pro2)

        // //再出结果之前，一定是挂起状态
        // console.log(pro2);//此时的Promise对象是挂起的，因为后续函数是异步执行的，但该处是同步执行的

        // // pro2.then(result=>console.log(result*2),err=>console.log(err*3));


        // const pro=new Promise((resolve,reject)=>{
        //     // resolve(1)
        //     // reject(1)
        //     throw new Error(0)
        // })

        // //后续处理函数没出错，则新的Promise对象是resolved状态；如果后续处理函数出错，则是新的Promise对象是rejected
        // const pro2=pro.then(data=>{
        //     console.log(data)
        // },err=>{
        //     throw 1;//抛出了错误，此时新的Promise为rejected状态
        // })

        // // pro2.then(data=>{//
        // //     console.log(1)
        // // },err=>{
        // //     console.log(err,"wrong")
        // // })
        // console.log(pro2)
        // console.log(pro)//rejected
    </script>
    </body>
</html>